# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://pitnotes.ru/"  # Include trailing slash
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2022, Все права защищены"
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "ru"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "категории"
tag = "тэги"
# series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
